# Turn off email notifications
notifications:
  email:  false

# Language setup
language: android

# JDK version
jdk:  oraclejdk7

# Emulator vars
env:
  global:
    - TERM=dumb
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

# Environment info
before_install:
  - chmod +x gradlew
  - ./gradlew -v
  - uname -a

android:
  components:
    # Use the latest tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # Use the given SDK version
    - android-23

    # Additional components
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license-.+'

script: ./gradlew clean build connectedCheck --info
