language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-21

before_install:
    # for gradle output style
    - export TERM=dumb

    # environment info
    - ./gradlew -v
    - uname -a

script: ./gradlew clean build
