# Turn off email notifications
notifications:
    email: false

# Language setup
language: android

# JDK setup
jdk: oraclejdk7

# Turn off caching and sudo
cache: false
sudo: false

# Emulator vars
env:
    global:
        - TERM=dumb
        - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
        - ANDROID_TARGET=android-22
        - ANDROID_ABI=armeabi-v7a

# Environment info
before_install:
    - chmod +x gradlew
    - ./gradlew -v
    - uname -a

# Android component setup
android:
    components:
        # Use the latest tools
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-22.0.0

        # The SDK version used to compile your project
        - android-22

        # Emulator image
        - sys-img-$ANDROID_ABI-$ANDROID_TARGET

    licenses:
        - 'android-sdk-license-.+'

before_script:
    # Create and start emulator
    - ps auxww
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script: ./gradlew clean build connectedAndroidTest --info
